site_name: Indira campaign guide

nav:
- 'Introduction': 'README.md'
  - 'Introduction': 'README.md'
    - 'License': 'LICENSE.md'
      - 'License': 'LICENSE.md'
#    - 'About': 'about.md'

theme:
    name: mkdocs
#    custom_dir: my_theme_customizations/
#    static_templates:
#        - sitemap.html
#    include_sidebar: true

docs_dir: 'docs'
site_dir: 'site'