site_name: Indira campaign guide

nav:
    - 'Boring stuff': 'README.md'
      - 'About this document': 'README.md'
      - 'License': 'LICENSE.md'
    - 'The campaign':
      - 'Indira':
        - 'Ayumu':
          - 'Brovook':
            - 'About Brovook': 'brovook/about.md'
          - 'Farquill':
            - 'About Farquill': 'farquill/about.md'
        - 'Nimia':
          - 'Lugra':
            - 'About Lugra': 'lugra/about.md'
          - 'Far point':
            - 'About Far point': 'farpoint/about.md'
          - "Badger's rise":
            - "About Badger's rise": 'badgersrise/about.md'
#    - 'About': 'about.md'

theme:
    name: mkdocs
#    custom_dir: my_theme_customizations/
#    static_templates:
#        - sitemap.html
#    include_sidebar: true

docs_dir: 'docs'
site_dir: 'site'