site_name: Indira campaign guide

nav:
    - 'Introduction': 'readme.md'
#    - 'User Guide': 'user-guide.md'
#    - 'About': 'about.md'

theme:
    name: mkdocs
#    custom_dir: my_theme_customizations/
#    static_templates:
#        - sitemap.html
#    include_sidebar: true

docs_dir: 'docs'
site_dir: 'site'