site_name: Indira campaign guide

nav:
    - 'Introduction': 'README.md'
    - 'more stuff': 'BLEH.md'
    - 'License': 'LICENSE.md'
    - 'The campaign':
      - 'Indira':
        - 'Ayumu':
          - 'Brovook':
            - 'About Brovook': 'README.md'
          - 'Farquill':
            - 'About Farquill': 'README.md'
        - 'Nimia':
          - 'Lugra':
            - 'About Lugra': 'README.md'
          - 'Far point':
            - 'About Far point': 'README.md'
          - "Badger's rise":
            - "About Badger's rise": 'README.md'
#    - 'About': 'about.md'

theme:
    name: mkdocs
#    custom_dir: my_theme_customizations/
#    static_templates:
#        - sitemap.html
#    include_sidebar: true

docs_dir: 'docs'
site_dir: 'site'